apiVersion: skaffold/v2beta11
kind: Config
build:
  artifacts:
    - image: gcr.io/vicnastea/cs-redirector-update
deploy:
  kubectl:
    manifests:
    - util/rbac.yaml
    - util/job.yaml
    - service.yaml
